FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

RUN apt-get update \
    && apt-get install -y chromium chromium-driver \
    && rm -rf /var/lib/apt/lists/* \
    && npm install

COPY . .

ENV BASE_URL=http://localhost:8081
ENV CHROME_BINARY_PATH=/usr/bin/chromium

CMD ["npm", "run", "test:selenium"]